language: java
mvn install:install-file -Dfile=C:\Users\spring-context-support-4.3.6.RELEASE.jar -DgroupId=org.springframework -DartifactId=spring-context-support -Dversion=3.1.0.RELEASE -Dpackaging=jar
install:
  - mvn install
jdk:
  - oraclejdk8